name: pybilt
channels:
- defaults
- conda-forge
dependencies:
- backcall=0.1.0=py_0
- biopython=1.72=py36_0
- bleach=2.1.4=py_1
- cftime=1.0.1=py36h7eb728f_0
- curl=7.61.0=h93b3f91_2
- decorator=4.3.0=py_0
- entrypoints=0.2.3=py36_2
- gmp=6.1.2=hfc679d8_0
- griddataformats=0.4.0=py_0
- gsd=1.5.3=py36h7eb728f_1
- hdf4=4.2.13=0
- hdf5=1.10.2=hc401514_2
- html5lib=1.0.1=py_0
- ipykernel=4.9.0=py36_0
- ipython=6.5.0=py36_0
- ipython_genutils=0.2.0=py_1
- ipywidgets=7.4.2=py_0
- jedi=0.12.1=py36_0
- jinja2=2.10=py_1
- joblib=0.12.5=py_0
- jsonschema=2.6.0=py36_2
- jupyter_client=5.2.3=py_1
- jupyter_console=5.2.0=py36_1
- jupyter_core=4.4.0=py_0
- krb5=1.14.6=0
- libgfortran=3.0.0=1
- libnetcdf=4.6.1=h5e45101_3
- libsodium=1.0.16=h470a237_1
- libssh2=1.8.0=h5b517e9_2
- markupsafe=1.0=py36h470a237_1
- mdanalysis=0.18.0=py36_0
- mistune=0.8.3=py36h470a237_2
- mmtf-python=1.1.2=py_0
- msgpack-python=0.5.6=py36h2d50403_2
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py_1
- netcdf4=1.4.1=py36h62672b6_0
- networkx=2.2=py_0
- pandoc=2.2.2=1
- pandocfilters=1.4.2=py_1
- parso=0.3.1=py_0
- pexpect=4.6.0=py36_0
- pickleshare=0.7.4=py36_0
- prometheus_client=0.3.1=py_1
- prompt_toolkit=1.0.15=py_1
- ptyprocess=0.6.0=py36_0
- pygments=2.2.0=py_1
- pyzmq=17.1.2=py36hae99301_0
- qtconsole=4.4.1=py36_1
- send2trash=1.5.0=py_0
- simplegeneric=0.8.1=py_1
- terminado=0.8.1=py36_1
- testpath=0.3.1=py36_1
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py_1
- webencodings=0.5.1=py_1
- widgetsnbextension=3.4.2=py36_0
- zeromq=4.2.5=hfc679d8_5
- atomicwrites=1.2.1=py36_0
- attrs=18.2.0=py36h28b3542_0
- blas=1.0=mkl
- ca-certificates=2018.03.07=0
- certifi=2018.8.24=py36_1
- cycler=0.10.0=py36_0
- dbus=1.13.2=h714fa37_1
- expat=2.2.6=he6710b0_0
- fontconfig=2.13.0=h9420a91_0
- freetype=2.9.1=h8a8886c_1
- glib=2.56.2=hd408876_0
- gst-plugins-base=1.14.0=hbbd80ab_1
- gstreamer=1.14.0=hb453b48_1
- icu=58.2=h9c2bf20_1
- intel-openmp=2019.0=118
- jpeg=9b=h024ee3a_2
- jupyter=1.0.0=py36_6
- kiwisolver=1.0.1=py36hf484d3e_0
- libedit=3.1.20170329=h6b74fdf_2
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=8.2.0=hdf63c60_1
- libgfortran-ng=7.3.0=hdf63c60_0
- libpng=1.6.34=hb9fc6fc_0
- libstdcxx-ng=8.2.0=hdf63c60_1
- libuuid=1.0.3=h1bed415_2
- libxcb=1.13=h1bed415_1
- libxml2=2.9.8=h26e45fe_1
- matplotlib=2.2.3=py36hb69df0a_0
- mkl=2019.0=118
- mkl_fft=1.0.4=py36h4414c95_1
- mkl_random=1.0.1=py36h4414c95_1
- mock=2.0.0=py36_0
- more-itertools=4.3.0=py36_0
- ncurses=6.1=hf484d3e_0
- notebook=5.6.0=py36_0
- numpy=1.15.1=py36h1d66e8a_0
- numpy-base=1.15.1=py36h81de0dd_0
- openssl=1.0.2p=h14c3975_0
- pandas=0.23.4=py36h04863e7_0
- patsy=0.5.0=py36_0
- pbr=4.2.0=py36_0
- pcre=8.42=h439df22_0
- pip=10.0.1=py36_0
- pluggy=0.7.1=py36h28b3542_0
- py=1.6.0=py36_0
- pyparsing=2.2.0=py36_1
- pyqt=5.9.2=py36h22d08a2_1
- pytest=3.8.0=py36_0
- python=3.6.6=hc3d631a_0
- python-dateutil=2.7.3=py36_0
- pytz=2018.5=py36_0
- qt=5.9.6=h8703b6f_2
- readline=7.0=h7b6447c_5
- scikit-learn=0.19.1=py36hedc7406_0
- scipy=1.1.0=py36hfa4b5c9_1
- seaborn=0.9.0=py36_0
- setuptools=40.2.0=py36_0
- sip=4.19.12=py36he6710b0_0
- six=1.11.0=py36_1
- sqlite=3.24.0=h84994c4_0
- statsmodels=0.9.0=py36h035aef0_0
- tk=8.6.8=hbc83047_0
- tornado=5.1=py36h14c3975_0
- wheel=0.31.1=py36_0
- xz=5.2.4=h14c3975_4
- zlib=1.2.11=ha838bed_2
